name: custom_wifi_info_plugin
description: Wifi info wrapper android plugin,serves as a
  bridge from flutter currently to android native code to retrieve Network info.

version: 2.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  plugin:
    androidPackage: com.vtechjm.wifi_info_plugin
    pluginClass: WifiInfoPlugin


